### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by RuneBergh** [Genivia/ugrep#6] opened 2019-11-05 14:11 UTC
segmentation fault when searching using wildcards and matching multiple files? for example  with path 2019-01-01/conn*. Ran into this issue trying to search all logs for an entire month.

**Comment by RuneBergh** [comment] 2019-11-05 14:33
From debugging: 

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `ugrep -ozrFf test /aaaa/bbbb/cccc/dddd/2019/2019-01-01/app_stats.00:00:00-01:0'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:522
522     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
[Current thread is 1 (Thread 0x7f525a7fc700 (LWP 19609))]
(gdb) where
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:522
#1  0x0000000000000000 in ?? ()
(gdb) bt full
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:522
No locals.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

So it looks like the issue is the length of the path to the file or? Baecause it was invoked with :
time ugrep -ozrFf test /aaa/bbbb/cccc/dddd/2019/2019-01-01/*

**Comment by genivia-inc** [comment] 2019-11-05 16:10
Could it be this? https://support.f5.com/csp/article/K88628547

Just in case, I will run some more memory tests to detect potential issues.

**Comment by genivia-inc** [comment] 2019-11-05 18:29
Thanks for reporting this. Found the problem in the decompression stream class `src/zstream.hpp` and will release an update momentarily.

**Comment by genivia-inc** [comment] 2019-11-06 02:27
The problem is fixed in v1.5.5.

**Closed by genivia-inc** 2019-11-06 02:27 UTC
