### ISSUE TITLE
-A may not show the context line for this pattern

### ISSUE THREAD

**Issue by firasuke** [Genivia/ugrep#383] opened 2024-04-09 20:07 UTC
Hey there,

I've been using `ugrep` for a while now without issues, but I stumbled upon the following issue when running:

```Sh
ugrep -rnw . -e ".*SOME_PATTERN.*" -A1
```

The `-A` option is not being parsed, or is not working, as `ugrep` isn't showing any context after the matched pattern, whereas `grep` is doing that successfully.

Any ideas what could be causing this issue?

**Comment by genivia-inc** [comment] 2024-04-09 20:20
I don't think that is a problem caused by any combinations of options, because none of the other options have any effect on the context. If anything differs or matters, it is the pattern itself, which is also modified with `-w` to match words using anchors.

Since we don't have your test case, you need to help us out here a bit. Can you be a bit more specific? Are after contexts always missing, or in some cases and when?

**Comment by firasuke** [comment] 2024-04-09 21:10
Here's the pattern I am using.

With `grep`:
![image](https://github.com/Genivia/ugrep/assets/46160727/4bf523ae-dd7a-406a-b570-b99f528540f7)

With `ugrep`:
![image](https://github.com/Genivia/ugrep/assets/46160727/7aabbeba-cc09-492c-974a-7e4a1d3c8c61)

**Comment by genivia-inc** [comment] 2024-04-10 00:29
Looks like there is an "off by one" problem, where the match position counter is off by one and that messes with the context position that no longer aligns. I also see the issue with `.*`, but not with different patterns even when those match the same initial part of a pattern. To show the differences, note the second search shows the context:

<img width="578" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/2d3c3c86-c8ce-400a-89a1-17a8b66acb35">
 
With a bit of tracing I found out that the difference between these cases is observable only in parts that actually _do not match_, like in the after context line. The internal pointer/position is moved by one so the context is no longer the same.

So it flew under the radar since pattern matching is OK, but the after contexts are not when this pattern is used. The "off by one" problem is triggered with the initial used of `.*` in a pattern and affects the after context.

The fix is actually very simple. The "off by one" happens in the pattern matcher, which is in an optimization that scans ahead when nothing possibly matches. The fixed version is correct:

<img width="578" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/9b40d624-587d-44b6-aa75-fff3a2abfe45">

Sorry for the trouble this may have caused. Glad you found this and shared it with us! An update will be released soon after a more testing to verify everything.

**Closed** 2024-04-10 13:28 UTC
Labels: problem

**Comment by firasuke** [comment] 2024-04-10 16:04
> Sorry for the trouble this may have caused. Glad you found this and shared it with us! An update will be released soon after a more testing to verify everything.

Yeah, no worries. Thanks for your time and effort on this project.

Keep up the good work!
