### ISSUE TITLE
Truncate really long lines in results

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#89] opened 2020-12-27 21:14 UTC
_Disclaimer: I know it's not `ugrep`'s problem_

Sometimes, when grepping through _the world_, it's not uncommon to hit really long one-liner files (think of e.g. minified `js` files).

I would like a flag that would make sure that each result (including any potential "output around it", if possible) would fit exactly one line (obviously, it could be just a default, it could accept an optional argument of maximum # of lines/chars).

I know I could pipe this to a `less` ... but I am too lazy; I will need to remember to pass `--color=always` (mostly due to the fact that _I have to type it manually in full_)

**Comment by genivia-inc** [comment] 2020-12-28 20:55
Searching through files with very long lines in the query UI can be improved by wrapping the lines. Is that what you're looking for?

The `--pager` wraps text to the screen, but the query UI keeps each line "as is" without wrapping.

**Comment by stdedos** [comment] 2020-12-28 23:01
> Searching through files with very long lines in the query UI can be improved by wrapping the lines. Is that what you're looking for?

While I should've thought that (and love it), "somehow it doesn't stick to me". `¯\_(ツ)_/¯`


> The `--pager` wraps text to the screen, but the query UI keeps each line "as is" without wrapping.

Pager is indeed a useful addition I haven't noticed before. However, I think its pager, if it's `less`, should have `-S` (chop long lines) on by default. On my case, file `~/.pip/zsh-cache` shreds even `less` pagination, so much so that you need to be extra-slow when scrolling that part on-screen, if you want to look at a "somewhat responsive" output (regardless of `-S`).

Or, it could optionally read a `UGREP_PAGER` env variable, and invoke that as a pager, instead of the system default.

Ultimately what I would want, is something like the main feature `smartless` (https://github.com/stefanheule/smartless) offers; don't switch to pager if less-than-screen%-lines are printed (additionally, in ugrep's case, if also there are no crazy-width-lines).

**Comment by genivia-inc** [comment] 2021-01-03 20:30
> Pager is indeed a useful addition I haven't noticed before. However, I think its pager, if it's less, should have -S (chop long lines) on by default.

To answer your question, the pager is `less` by default and wraps lines.

**Comment by NightMachinary** [comment] 2021-05-31 11:42
@genivia-inc How do I wrap the lines in the interactive query mode?
![image](https://user-images.githubusercontent.com/36224762/120188151-0187ee80-c22b-11eb-8778-e90cbc53c38d.png)

**Comment by genivia-inc** [comment] 2021-05-31 15:27
Query mode does not wrap lines (by default). But the UI is reactive, so rescaling the window size works as well as SHIFT cursor left/right to pan the view left/right. The query UI was intended to greatly speed up the search process compared to the command-line. File viewing is still best done with e.g. `more` or `less`.

So to actually read the matching file(s), assign CTRL-Y to `more` (or `less`) e.g. with `GREP_EDIT=less` so that pressing CTRL-Y gives you the full view of the file with `more` (or `less`). By default, CTRL-Y opens an editor but you can assign anything you want, of course.

**Comment by NightMachinary** [comment] 2021-05-31 17:47
@genivia-inc Is there an option to make it wrap lines? Rescaling the window is not a solution, as the text would become too small to read. Horizontal scrolling is also a very bad UX. 

Using `C-y` has two problems:
- The search seems to reset when I do `C-y`, i.e., it starts the search from the beginning and loses the currently found matches.
- The file is not opened at the line it has matched.

In general, opening an editor to view the file introduces too much friction. The whole point of the query mode is to have a way to do fast, incremental instant searches.

**Comment by stdedos** [comment] 2021-05-31 17:52
If you are going to change/improve how query mode works, my .02$ on _how I imagine it_: I would like to make a search, and then take that search intact (including any possible highlighting) and further filter it.

(I'm not saying that it has strictly to do with the above request - I only wanted to plan a seed if you end up changing Query mode as a result to the above comments)

**Comment by genivia-inc** [comment] 2021-05-31 18:57
> If you are going to change/improve how query mode works, my .02$ on how I imagine it: I would like to make a search, and then take that search intact (including any possible highlighting) and further filter it - independently.

I think we all agree that these suggestions and ideas are excellent. The intent of the UI is allow users to easily refine query patterns "on the go". That's the strength of the UI compared to the command line, because I don't know anyone who likes to repeatedly edit the command line patterns and run the `grep` command over and over again to get the desired results. The UI is much faster and easier IMHO.

That's also why I've updated the TAB behavior in the UI to address one of our important use cases to search lots of archives for source code matches: once a set of files with option `-l` is identified with specific patterns, a file or directory in the listing can be selected with TAB so that the current pattern can be expanded or even narrowed to search that specific file or directory. The flow of this method works best by switching `-l` on with `ALT-l` to produce the list, then TAB then switch `-l` off with `ALT-l`. This makes the search in that file or directory totally _independent_ of the initial search to get to that file or directory. Then we can go back up one dir with SHIFT-TAB.  I wonder how many users are aware of this feature and the workflow that works well for us?

I've been thinking that SHIFT-TAB to go back up one dir should maybe also restore the previous regex pattern and options. Is that useful? Does that help?

> and then take that search intact (including any possible highlighting) and further filter it - independently.

To filter on a line-by-line basis, the `--bool` option can help to narrow the search results further. Applying a `--bool` option to the whole file would be useful as suggested in #113 (in the planning phase, because other ugrep things had a higher priority). That feature would improve the suggestion above to be able to narrow down the search results further on a per-file basis in addition to line-by-line Boolean queries.

**Comment by stdedos** [comment] 2021-05-31 19:17
I envision the TUI as a linked (pipeline), tabbed interface: You make search one, you open a new tab, you refine the search, etc etc. You can edit any tab (search refinement / pipeline) independently of the others . 

Therefore, in my mind, Tab/Shift+Tab is useful (navigating the tabs). 
Although (depending on the TUI layout, Terminal Emulator used etc), you may want to use some PgUp/PgDown combination (and leave tab for "completion"-like accelerators). 

To be honest, I'll need to read your comment again, with a clearer mind to understand your idea better (and to apply/modify my idea to your vision).

**Comment by genivia-inc** [comment] 2021-05-31 20:06
> You make search one, you open a new tab, you refine the search, etc etc. You can edit any tab (search refinement / pipeline) independently of the others .

Sure, and that approach makes the "un-TAB" (SHIFT-TAB) more logical to restore the regex pattern and options, since these apply to the TAB specifically, the original pattern and options aren't changed.

Implementing a tabbed view with the current UI (or TUI to be more precise as you point out, though I personally don't like that abbrev) could be done without relying on other libraries. It's simply adding a new top line to the screen window that shows to tabs with the rightmost being actively displayed in the window, kind of like a stack of directory tree branches, one TAB per branch. TAB opens a new tab and SHIFT-TAB closes it to go back the parent tab, or perhaps ESC can be updated to quit a tab and quit the program when at the top level. Seems logical. Note that TAB already shows the directory path so one can view each subdir along the path as a tab.

I don't know if you have this in mind or a UI with "free tabs" like a Web browser. But that clutters the UI perhaps and multiple views can already be accomplished by simply opening more terminal windows with ugrep, right?

**Comment by NightMachinary** [comment] 2021-05-31 20:25
@genivia-inc That `TAB` feature seems cool. I agree that it is more intuitive if it does restore the previous regexes. The whole tab/stack view seems a good way to represent the idea in the UI. I am a bit confused on how it chooses which file is currently 'selected' though. (There are multiple files on the screen, does it just open the topmost one?)


> I would like to make a search, and then take that search intact (including any possible highlighting) and further filter it - independently.

@stdedos I also think this is covered by using `--bool`. You would just type a space and add your new patterns to further refine the search.

**Comment by stdedos** [comment] 2021-05-31 20:28
> SHIFT-TAB closes it to go back the parent tab

I don't necessarily like _closes_; I prefer _navigates_ (as in "I can go back and forth"). You can _close_ with ESC if you want. 

Example thought process: 
I am searching for "expected", oh-yeah! that contains "class", that references "fabric" (not on the same line as the previous ones), errrrr ~~that contains "class"~~ I meant "module"; oh good I found it "Enter" (copy the path? open the file?); I'm done ugrep, thanks ❤️; ESC ESC ESC (or Ctrl-Q? 😕) 

> I don't know if you have this in mind or a UI with "free tabs" like a Web browser. 
"The closest that you can bring a web browser onto a TUI"; i.e. free floating tabs is not a requirement 😝 

I tried to frame the cascading filters logic UX in a UI. Given the limited space on a terminal, the closest I could describe the "always-visible, meaningfully outlining individual steps" kind of UI was tabs on a browser: each one has a title, and you can switch to them to your whim (and even re-order them, if you'd want to code it 😂). 

In the design we are discussing for ugrep, the difference from a web browser is that the "tabs" are not independent, but they take input, and filter it to produce an output (which can be the input of a next step). 
And ofc ugrep is a terminal application - no free-floating tabs required 😝

**Comment by genivia-inc** [comment] 2021-06-01 14:17
> @NightMachinary Using C-y has two problems:
> - The search seems to reset when I do C-y, i.e., it starts the search from the beginning and loses the currently found matches.

Not sure what you mean? The pattern is not changed. The matching files are shown again from the first on, but setting a bookmark with CTRL-X before CTRL-Y avoids that, just return with CTRL-R. Perhaps CTRL-Y should set the bookmark and automatically return to the same spot?

> - The file is not opened at the line it has matched.

That will be difficult to achieve because editors and pagers have their own conventions to accept a line number to start the view.

> In general, opening an editor to view the file introduces too much friction. The whole point of the query mode is to have a way to do fast, incremental instant searches.

But opening with `less` assigned to CTRL-Y (setting `GREP_EDIT`) instead of an editor is super easy, no? If you need to edit then `less` invokes an editor when you press `v`.

The UI is intended to simplify searching files on a line-by-line basis and to refine the search until the desired file(s) are located. Then pressing ENTER and A before CTRL-Q dumps it all out back to the terminal or to a pipe.

IMHO viewing files is really best delegated to another tool like `less` that is specifically designed for this.

**Comment by NightMachinary** [comment] 2021-06-01 15:16
@genivia-inc 

> The matching files are shown again from the first on, but setting a bookmark with CTRL-X before CTRL-Y avoids that, just return with CTRL-R. Perhaps CTRL-Y should set the bookmark and automatically return to the same spot?

I thought the search was restarted (i.e., `ugrep` is scanning the disk again) by `C-y`? I am not sure. It is a good idea to set the bookmark automatically though.

> That will be difficult to achieve because editors and pagers have their own conventions to accept a line number to start the view.

I think you can add an option, `--editor-with-linenumber`, then use `filename:LINENUMBER`. The user can write their own wrapper scripts to convert from this input to the one their editor expects. I myself use an `emacs.dash` wrapper script to handle these sorts of things.

> But opening with less assigned to CTRL-Y (setting GREP_EDIT) instead of an editor is super easy, no?

It is if your goal is to find some specific file and then do a lot of work on it. 

If you just want to search for some info, a Google-style UI where you see a bunch of results with some context is much better. Most such searches do not need anything more than that. Another example of this kind of search is http://hn.algolia.com/ . 

The key point is that:
- There are a lot of false-positive results that can be quickly eliminated if their context is visible
- Even the desired results usually do not need anything more than the few lines displayed in the summary to deliver their value to the user.

Pressing `C-y` on each result, and the latency of `less` opening and closing, are just pure overhead in these conditions that add no value.

It's a different workflow, but I think `ugrep` can do it well without compromising `to simplify searching files on a line-by-line basis and to refine the search until the desired file(s) are located.`

**Comment by genivia-inc** [comment] 2021-06-01 20:32
These are all good suggestions, but we're really talking about many different things here.

1. viewing a file that matches the search criteria, i.e. shown in the UI by pressing CTRL-Y
2. editing a file that matches the search criteria, i.e. shown in the UI by pressing CTRL-Y
3. making CTRL-Y automatically jump back to the same spot in the search results afterwards
4. wrapping text in the screen UI view
5. using TAB to navigate to directories and files (and back)
6. restoring the pattern and options after a TAB view (back with SHIFT-TAB or perhaps ESC)
7. refine searches in tabbed views, update TAB behavior or not? (Already can use `--bool` to add more constraints)
8. Letting `--bool` match anywhere in the file, not only line-by-line as in #113

These all have different goals and usage scenarios that fit these goals. So let's not muddy the waters and tackle only one at a time. If I do not get actionable feedback on my questions, then I will drop the whole idea of pursuing any of these ideas. Ideas are subjective and need to be evaluated for their merit and practical applicability that may require compromises. Development is often a matter of compromises due to tradeoffs.

My comments and concerns:

1 and 2 are done with CTRL-Y where 3 will be an easy improvement. Actually, pressing CTRL-R after CTRL-Y already works, but it's probably better to make it automatic. Making CTRL-Y jump the the line to view or to edit is impossible, because this information is no longer available in the screen view: the line number information can only be obtained by "screen scraping" it from the ugrep output. This is the way the filename is extracted and internally the filenames are marked with NUL characters to make this process reliable. But "screen scraping" the line number could be unreliable in practice I'm afraid. Note the 3 required a new search when the file in question was edited and updated results should be displayed. Perhaps not so when CTRL-Y invokes `less` without changing the file. But even that is a fallacy: with `less` you can edit the file by pressing `v` so ugrep has to be run again. Note: perhaps checking the file's time stamp may make things a bit quicker though, so I'll look into that.

3 is perhaps possible using a special key combination to switch back/from wrapped text view. But practically when trying a prototype some time ago I ran into implementation problems and issues that cause bugs. For example, long pathnames/filenames will be truncated (in the text buffer for the display) so CTRL-Y, CTRL-W and CTRL-S won't work reliably any longer. Development is for a large part an art of avoiding the introduction of new bugs, no? The important claims that ugrep has no limits is key here, because if we cannot handle huge files of a couple of gigs then we are toast. Buffering an entire file searched or buffering all search results produced by ugrep in memory is also out of the question. That's why there are tradeoffs and compromises to be made when considering improvements. There is no such thing as a "free lunch" with advanced utilities (not toys) that must meet their functional and non-functional requirements.

5 the current implementation of TAB takes the topmost directory/file shown on screen to navigate to. The current working path is shown as feedback. This works very well in our usage scenarios to refine the search for specific projects by navigating to them. SHIFT-TAB navigates back up one directory or out of the current single file searched. It is really radically simple when starting with `ug -lQ` to list the matching files, then TAB into subdirectories. When reaching the file to view just type `ALT-l` (or `ALT-y` to view the file). Just try it. I think 6 as an improvement makes the most sense here, because we don't have to type `ALT-l` again or restore the pattern to continue searching elsewhere. I think that TAB is just so new as an approach that nothing else compares? That is not bad. It is just totally new and needs some getting used to. But once you get used to it, this workflow is really easy and powerful to be able to change directories on the fly and refine the search as needed.

7 this is an interesting idea, but should be tied with 4 and 5 somehow. Again, try TAB so we can figure out what might be possible.

8 this can be done but takes a bit of time to further investigate, see #113, because of potential performance ramifications. I also want to play with other tools to get a feel what works best in terms of options. For example, we can either add `--bool-all` with a pattern to match the files, and then also allow `--bool` or the usual regex patterns to match per line (so TWO independent criteria), or `--match-all` to radically change the way pattern matching works, but when not done right that can be counter intuitive and even confusing (see my comments in #113). Note that `-M` is kind of like the former "TWO independent criteria", because files are selected based on their "magic" first bytes, then the regex patterns are matched and shown. However, if we go the route to add `--bool-all` why not add a programmatic approach that allows you to define file-wide conditions much more precise? For example, "if a line matches X then Y should match else Z should match" (like control flow, but declarative like Prolog `X -> Y ; Z`). One can build a whole "programming" language on top of this so users can specify a powerful set of file-wide search criteria.

@NightMachinary, some things need to be clarified:

> Pressing C-y on each result, and the latency of less opening and closing, are just pure overhead in these conditions that add no value.

No, it isn't expensive or has no value: if you want to view the whole file without messing with the regex pattern or options, how do you suggest this can be done without something like CTRL-Y? I'm just curious.

> There are a lot of false-positive results that can be quickly eliminated if their context is visible

Sure, but that is what we have, a couple of lines showing matching text. The next step to refine the search for higher accuracy is a different matter. That's the big idea of using TAB. This is unrelated to CTRL-Y or specific file viewing with text wrap etc.

> If you just want to search for some info, a Google-style UI where you see a bunch of results with some context is much better. [...] Even the desired results usually do not need anything more than the few lines displayed in the summary to deliver their value to the user.

Sorry, I am lost here. On the one hand, you're saying that it is OK to view a few lines, but on the other hand you want to view the whole file too? Or is it like a Google search you mentioned to see some results and then clicking on the link to view the page? But that is the same as CTRL-Y to view the file. Which is not what you like to use. What is wrong with that? Am I missing something?

**Comment by stdedos** [comment] 2021-06-01 21:03
> Note the 3 required a new search [...] so I'll look into that.

Not your problem I'd say. User can manually re-initiate a scan if he wants (if that means a full scan), or you can just re-process the file automatically (if you can process just one file).

> 5 the current implementation of TAB takes [...] and refine the search as needed.

My problem is I don't know what I am looking for. I remember random strings that can be **anywhere**. And I have **so many ways** of breaking "optimizations".

- I am looking for a setting. That setting can be e.g. under `.config`. Oops, 0 results (or worse, multiple unrelated results!) if hidden directories are excluded.
- I am looking for a function name in a project. However, that project is checked out twice (or thrice!) under ~, and also once inside a VM. OOPS, unless I remember to `-I`, binary files are searched, and it's somewhere in that binary file (let alone the **tremendous** delay of searching GB++-long binary files) - which is search first due to been closer to `~` than `~/Documents/projects/client/project/a/`
- I am looking for a note that I have made about `colout` pypi python package. OOPS, I have zsh-completion activated, which stores completion data directly in ~, as a space-separated ASCII file.
NOTHING can save me - I need to compile a master exclude list. e.g. including `.venv/*`, `.git/*`, etc ...
OOPS, `.git/config` is a valid file - and let alone the (luckily few) times I will be trying to be digging binary objects in `.git/` for a commit that's not reasonably diggable using reflog ....

Cascade filtering (and interactive ignore-binary-files toggle) usually works best for me.

> 8 this can be done but takes a bit of time to further investigate, see #113, because of potential performance ramifications. ...

By defining cascade filtering, you will need to define what data passes on to the next stage (which I imagine will include filenames, and the matched string). After you highly refine the search results (_assuming the user filtered `max(<<1% * elements, 1M)` of the total pool of data_) - then applying additional filters should not be that penalizing performance. You can also consider parallelization - once a file cleans the first pipeline, a new thread can start working on it on the second pipeline etc

> For example, "if a line matches X then Y should match else Z should match" (like control flow, but declarative like Prolog `X -> Y ; Z`). One can build a whole "programming" language on top of this so users can specify a powerful set of file-wide search criteria.

I'm thinking YAGNI, but, if you can somehow isolate this (from every aspect, including e.g. performance) from the main purpose of grep (even if it's on steroids) - then, sure, why not?

My idea has the benefit that you can use the same building blocks - you just need to define the boundaries and the communication bus well. Having these properties, it sounds more intuitive to me (I just keep grepping files on top of a previous grep)

---

I am well invested (as you can see) in my idea; if you want, we can pull it into a separate ticket.
Then, I am all-ears to answer your design questions. If you feel that I am not responding to your RFC, then you can ping me.

This discussion, while very desirable, it is (as you dully noted) 8 separate ones 😛
I cannot keep track of my stuff, dev's stuff, others stuff, the ideas and the connections among them 😅

**Comment by stdedos** [comment] 2021-06-01 21:05
> `GREP_EDIT=less`

btw, please make this `UGREP_LESS`. It's yours; namespace it properly 😉

**Comment by stdedos** [comment] 2021-06-01 21:09
From https://github.com/Genivia/ugrep/issues/89#issuecomment-851637374
> I wonder how many users are aware of this feature and the workflow that works well for us?

For me that's not the case. Usually, I know _what I don't want_ - not what I want.

So, while it appears to be useful for use cases, that's never the case for me. Or, I already know it ahead of time. Or, I can just ` cd to/the/dir ; tput reset; !!` and restart.

**Comment by genivia-inc** [comment] 2021-06-01 23:50
> So, while it appears to be useful for use cases, that's never the case for me. Or, I already know it ahead of time. Or, I can just cd to/the/dir ; tput reset; !! and restart.

Hmm. That sounds way more laborious than pressing TAB to cd to the dir you want to got within ugrep.

**Comment by NightMachinary** [comment] 2021-06-01 23:50
@genivia-inc 

> Sorry, I am lost here. On the one hand, you're saying that it is OK to view a few lines, but on the other hand you want to view the whole file too? Or is it like a Google search you mentioned to see some results and then clicking on the link to view the page? But that is the same as CTRL-Y to view the file. Which is not what you like to use. What is wrong with that? Am I missing something?

My point was not that ctrl-y isn’t good (it is!); I was trying to communicate why ctrl-y isn’t a good replacement for having line wrapping in the query UI for my workflow. I like to have both the text wrapping and the jump-to-file capability.

> Note the 3 required a new search when the file in question was edited and updated results should be displayed.

I don’t see the value in updating the results after edits. The user just edited the file themselves, they don’t need to see the updates again. It’s a good luxury to have, but I wouldn’t care if it wasn’t there.

> Making CTRL-Y jump the the line to view or to edit is impossible, because this information is no longer available in the screen view: the line number information can only be obtained by "screen scraping" it from the ugrep output. This is the way the filename is extracted and internally the filenames are marked with NUL characters to make this process reliable. But "screen scraping" the line number could be unreliable in practice I'm afraid.

One workaround can be to just pass the text of the current line to the editor. The editor can then search and find the line that text occurs in. I have seen this approach used by org-mode links to link to arbitrary lines of a file without relying on line numbers, and it works well. 

(I don’t understand why scraping the line number is problematic though. Wouldn’t it be as simple as `^(/d+):`? I can even imagine prefixing each line with a metadata character that aids in the parsing, and coloring this character the same as the terminal’s background to avoid cluttering the UI.) 

> One can build a whole "programming" language on top of this so users can specify a powerful set of file-wide search criteria.

This seems a very promising idea! Is there any prior art?

**Comment by genivia-inc** [comment] 2021-06-02 20:11
In the meantime, I've committed an update with an improved `-Q` query UI TAB/SHIFT-TAB navigation to subdirectories. This update is aligned with the current documentation. It just improves the flow when using TAB/SHIFT-TAB and CTRL-Y. This update is in the master branch, because it makes sense to fold this into the upcoming v3.3.1 release. This update improves:

- TAB saves the current state of the search pattern, the current screen location (cursor) and the options/flags currently active.
- SHIFT-TAB navigates back to the parent dir and restores the pattern, cursor and options.
- CTRL-^ jumps back to the original working directory, restores the pattern, cursor and options.
- CTRL-Y checks if the file is changed, to speed up redisplay after view or edit when the file is not changed.
- CTRL-Y jumps back to the original search screen after viewing a file.

Setting `EDITOR` or `GREP_EDITOR` or `GREP_EDIT` to `less` works great (or to an editor like `vim` if editing is desirable). Add options to `less` to customize the view. Perhaps `GREP_VIEW` or a command line option (probably best) can be used to specify a UI viewer in a future update.

For example, `ugrep -lQ` shows a list of files. Enter a pattern then cursor down/up to select a file. TAB into the subdirectory and eventually into the file. At any time, the pattern and options/flag can be changed. SHIFT-TAB returns to the previous view. Basically, TAB and SHIFT-TAB move along the branches of the directory tree down and up, respectively.

We did some exploration with the improvement and this improved our workflow pretty well. It is also less laborious and more intuitive.

The other items on the list will be addressed eventually.

Feedback on this branch commit update and the suggestions above are welcome! This should be a community effort and not at all "dictated" by me, IMHO.

**Comment by genivia-inc** [comment] 2021-06-03 13:49
Another commit with a minor improvement: TAB followed by SHIFT-TAB from a single file search didn't restore the pattern. Now it does. This commit is part of the minor release update coming soon. Next I'll update the documentation, e.g. with suggestions for CTRL-Y to use a pager like `less` and perhaps rename `GREP_EDITOR` and/or add a command-line option to specify a viewer/editor for the UI. A major release will follow later with the other ideas discussed here become plans for a major update.

**Comment by genivia-inc** [comment] 2021-06-03 16:55
Just my 2c.

> @stdedos My problem is I don't know what I am looking for. I remember random strings that can be anywhere. And I have so many ways of breaking "optimizations".
> 
> - I am looking for a setting. That setting can be e.g. under .config. Oops, 0 results (or worse, multiple unrelated results!) if hidden directories are excluded.

I understand, but you can change almost any config setting within the query UI by pressing `ALT-key` or CTRL-Z to view the options and change them by pressing a few keys. For example, to enable hidden directories and files (dotfiles) just press `ALT-.`.

> - I am looking for a function name in a project. However, that project is checked out twice (or thrice!) under ~, and also once inside a VM. OOPS, unless I remember to -I, binary files are searched, and it's somewhere in that VM binary disk file (let alone the tremendous delay of searching GB++-long binary files) - which is search first due to been closer to ~ than ~/Documents/projects/client/project/a/

Options and flags can be changed at any time. It is recommended to enable `-I` by default to skip binary files. With the `.ugrep` config file just add `ignore-binary`. When search results hit a lot of compressed files that should not be interesting, then just disable compressed file search with `ALT-z`.

> - I am looking for a note that I have made about colout pypi python package. OOPS, I have zsh-completion activated, which stores completion data directly in ~, of all pypi packages on the internet, as a space-separated ASCII file.

See above.

> NOTHING can save me - I need to compile a master exclude list. e.g. including .venv/*, .git/*, etc ...
> OOPS, .git/config is a valid file - and let alone the (luckily few) times I will be trying to be digging binary objects in .git/ for a commit that's not reasonably diggable using reflog ....

See above.

If I may give a suggestion, you really want to use `ALT-l` to your advantage to get an initial grasp of what files have search hits! Then toss out binary files or compressed files if these do not seem relevant. Then the possibilities are wide open to work with regex patterns (including Boolean `--bool` with `ALT-%`) and options and using TAB to navigate to subdirectories to "zoom in" on a set of files there e.g. using more specific regex patterns. Then just SHIFT-TAB back. You can also set a bookmark with CTRL-X at a line that you want to navigate back to quickly with CTRL-R.

I am confident that the query UI can be further improved with new features, but those features should be very specific so they can be described in a requirements specification with some examples to make this more actionable.

On my wish list are:

- Viewing files with CTRL-Y should be the default rather than an editor. Unfortunately, on Windows the `more` command is very limited and will not work with CTRL-Y. I dread implementing a custom viewer in the UI, but...
- Restoring the CTRL-X bookmark that was set before navigation with TAB/SHIFT-TAB.
- Should CTRL-X bookmarking also restore the pattern and options? Right now, it just jumps to the bookmarked line but that line may no longer be the same if the pattern and options were changed. Restoring the pattern and options will produce a new search though, which adds a delay in that case. Basically, CTRL-X then stores the state rather than just a bookmarked line on the screen.
- Wrapping long lines in the UI, perhaps. But with a viewer (CTRL-Y) this may not be necessary. Perhaps open a split screen to view the matching file (i.e. the file on top of the list on the screen)? Or implement some wizardry with tmux perhaps?
- File-wide Boolean search patterns. With option `-l` this is super easy and efficient. It just checks a file for matches. But to show matching lines, this is not efficient and in the worst case the whole file is stored in memory e.g. when two AND patterns match, one at the start and one at the end of the file. In this respect, it is also not clear to me what the matching lines should show. I suppose any of the AND and OR patterns specified should be highlighted. For example, `A AND B AND C` shows lines that match `A` or `B` or `C` (note the _or_ here!) if the file has all three somewhere. So this is very different than `--bool` and is perhaps therefore best approached with a new option that relates to file selection, like what `--type` and `--magic` are also intended for.
- Tabbed windows with search results.

**Comment by genivia-inc** [comment] 2021-06-03 21:09
Another commit with the following additions and changes:
- Query UI CTRL-Y uses the `--view=COMMAND` option to use the specified COMMAND to view/edit a file shown at the top of the screen, or the environment variable `PAGER` when set or `EDITOR` when set.
- Query UI Tab/Shift-Tab improved as discussed.
- Query UI CTRL-X (set bookmark) and CTRL-R (restore bookmark) now also save and restore the state of the search to jump back to the bookmarked top row in the screen view. Bookmarking is also per Tab/Shift-Tab view, so old bookmarks are restored with Shift-Tab.

These changes are for evaluation purposes and will be released as v3.3.1 when all is OK. Let me know what you think.

**Comment by stdedos** [comment] 2021-06-04 06:58
> Just my 2c. [...] See above.
> 
> If I may give a suggestion, you really want to use `ALT-l` to your advantage to get an initial grasp of what files have search hits! Then toss out binary files or compressed files if these do not seem relevant. Then the possibilities are wide open to work with regex patterns (including Boolean `--bool` with `ALT-%`) and options and using TAB to navigate to subdirectories to "zoom in" on a set of files there e.g. using more specific regex patterns. Then just SHIFT-TAB back. You can also set a bookmark with CTRL-X at a line that you want to navigate back to quickly with CTRL-R.

The reason I do not usually get into these kind of arguments (as evident from https://github.com/Genivia/ugrep/issues/89#issuecomment-753671802), is that I don't need you to tell me how I should be doing stuff (no attack of any kind intended).

First of all, I would need to learn new key combinations - which I am not usually fun of.
Especially when it's identically the same that I could Ctrl-C, fix the flags and re-run - the majority of the time (i.e. busywaiting the search results) is already wasted.
I don't care about "get[ting] an initial grasp of what files have search hits" - so, now I'll waste two runs (of equal time e.g. `-l` not limiting the pool of a potential toggle-off) on getting the result I need, instead of one? 😕 I want _the_ result itself, not a pre-image.
Zooming on the files does not resonate with me.

True - I may be shedding "significant" time (5 seconds max?) when toggling flags, but I am not super-fun of the tmux-style pagination that does not propagate to the Terminal Emulator (or does not have the ala-tmux scrollback buffer).
And, any touch of the UI trashes the current result. I may think I needed a flag, but not anymore. There goes any result.

**Comment by genivia-inc** [comment] 2021-06-04 13:06
Quoting my comment:

> Viewing files with CTRL-Y should be the default rather than an editor. Unfortunately, on Windows the more command is very limited and will not work with CTRL-Y. I dread implementing a custom viewer in the UI, but...

We could also use `ugrep -Q --view="ugrep -Q"` to view a file with CTRL-Y by invoking another ugrep UI within the current UI. To make this even better, I can add a check if ug or ugrep is the view command and in that case pass options to the ugrep viewer to highlight the matches with `-e PATTERN` within the view. In this way the whole file can be viewed with matches highlighted with `-y`. That would be brilliant, especially when text wrap is added to the UI, eventually. This should work nicely on all platforms, including Windows.

**Comment by genivia-inc** [comment] 2021-06-04 13:49
@stdedos This thread has become the focus on improving the UI rather than line truncation of grep output. The UI already effectively "truncates" lines without actually losing them altogether, i.e. just pan to the right. So long Javascript single liners won't take up the whole screen.

> First of all, I would need to learn new key combinations - which I am not usually fun of.
> Especially when it's identically the same that I could Ctrl-C, fix the flags and re-run - the majority of the time (i.e. busywaiting the search results) is already wasted.
> I don't care about "get[ting] an initial grasp of what files have search hits" - so, now I'll waste two runs (of equal time e.g. -l not limiting the pool of a potential toggle-off) on getting the result I need, instead of one? 😕 I want the result itself, not a pre-image.

Your comments have me somewhat baffled, because it's just a suggestion, there is not a "rule" to use the UI in any specific way. The UI is sufficiently flexible to meet different usage scenarios.

It should be rather obvious from the man page on option `-Q` that:
- the UI keys are the same as standard grep options, just use ALT e.g. `ALT-l` to list files like option `-l`.  What is the problem to use grep's _existing options_ with ALT? It gets even better, because if you forgot what grep uses as options, just CTRL-Z to view and change options interactively. This is an easy reminder without getting the full man page.
- not sure what you mean by "pre-image"? I assume the list output with option `-l`. It's common to use `-l` if the number of matching files is huge to get an initial dump of possible matches, so it's not uncommon. In the UI just press `ALT-l` to switch back/forth to the list view. You do not have to use this, it's all up to you. There is no specific way you should do any of these things.
- "zooming in on files" is just a poor way of saying that there are some files we are interested in but we don't know which and where they are. Once located, these can be viewed one at a time, e.g. with CTRL-Y.
- while the UI may not be for everyone, the whole idea of the UI is to avoid tedious cycles of repeated grep runs and CTRL-C to change options and patterns on the command line. I was tired of doing just that. The UI has proven to speed up searching versus command-line grep restarts.

Inevitably, the UI will further improved with new features, but I doubt that ALT-key is hard to get used to for those that use grep already. The UI is similar to grepping with a pager, _but you do not have to quit the pager to change the grep pattern and options._

**Comment by genivia-inc** [comment] 2021-06-05 20:54
One minor annoyance is now more apparent when switching back with Shift-Tab or after CTRL-Y editing: the display may not start at the begin of the search results so it can be confusing why some results are missing (they are not).

Therefore, I propose to update the prompt line to display the position in the search, starting with 0:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/13117347/120905062-9c167200-c61d-11eb-865d-edba733a9041.png">

The number 0 is shown when we're at the start, but otherwise shows the number of rows (or lines) that are skipped and not shown, for example after moving 51 lines down:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/13117347/120905120-eef02980-c61d-11eb-8c0e-1c02370d9ca7.png">

This suggests we can cursor up or PgUp to see these "missing" lines.

Next, after pressing Tab you'll see the path to the directory now show up with the prompt (like we had before):

<img width="682" alt="image" src="https://user-images.githubusercontent.com/13117347/120905145-17782380-c61e-11eb-87f8-9a6b32e27c15.png">

Pressing Shift-Tab brings us back exactly where we were before by restoring the pattern and options and position of the screen, in this case with the number 51 indicating the position:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/13117347/120905120-eef02980-c61d-11eb-8c0e-1c02370d9ca7.png">

I think this will help to keep track of things better in the query UI.

**Comment by genivia-inc** [comment] 2021-06-09 13:38
Quick update: release v3.3.2 includes some UI improvements to keep track of the view's location, which is especially important after Shift-Tab and CTRL-R. The `--view=ugrep` update is not yet included but will be next on the agenda. This requires some engineering to pass the right options to the forked ugrep -Q viewer.

**Comment by genivia-inc** [comment] 2022-05-26 20:34
See also #199 with a new feature to highlight abbreviated matches with context with options `-o` and `-C`.

**Closed** 2022-05-29 18:13 UTC
Labels: enhancement, question
