### ISSUE TITLE
ugrep: warning: ... File name too long

### ISSUE THREAD

**Issue by NightMachinary** [Genivia/ugrep#180] opened 2021-12-27 14:25 UTC
I am getting a lot of errors when running my previously working scripts:
```
ugrep: warning: /Users/evar/.../log.org: File name too long
...
```

**Comment by genivia-inc** [comment] 2021-12-27 15:27
This is not a ugrep error message, but some file IO error generated somewhere by a C/C++ lib call, perhaps by `fopen()`. Strange, because there isn't a difference in `fopen()` calls except the mode parameter includes "b" as per recent Windows-related discussions on CRLF.

What OS is this? What ugrep version used to work?

**Comment by genivia-inc** [comment] 2021-12-27 15:44
Most likely a failure of the `stat()` or `lstat()` calls, because the literal warning message lacks some details that are normally shown. This warning only happens when `stat()` or `lstat()` fail, or if `GetFileAttributesW()` fails on Windows.

I doubt this is a regression issue because this part has been part of ugrep for quite some time now. There is a pre-pass over the command line file arguments to warn about non-existing files. This is done so that `-Q` will not start the UI if files are missing. Otherwise the problem with missing files will not be visible in the UI window.

**Comment by genivia-inc** [comment] 2022-01-04 17:23
I still need to know:

- What OS this is tested with?
- How long are the pathnames that are passed to ugrep as command line arguments?

The error is clearly generated by libc `stat()` function that takes a string pathname, the pathname passed to ugrep as command line arguments. It is unlikely to produce this error (and I've never seen it before), so I am curious why and when this happens.

**Comment by NightMachinary** [comment] 2022-01-04 18:05
Sorry for the delay. My initial report was also pretty bad, I guess I had been sleepy then.

- macOS 11.2.1
- ugrep 3.4.0 x86_64-apple-darwin20.6.0 +sse2 +pcre2_jit +zlib +bzip2 +lzma

I am no longer getting the errors, so I don't know why the error had suddenly appeared at that time. The reason I elided the pathnames was because they contained some semi-sensitive information. I can email the whole command invocation to you, but it's something like:
```
ugrep --bool --smart-case '--sort=best' --no-confirm --perl-regexp --hidden '--binary-files=without-match' --perl-regexp '--format=* [[highlight:,default,file_point:%f::%b][%f]]%~** %[1]#%~' --line-number --with-filename '--max-count=1' '/Users/evar/cellar/notes/x/y/z/x/y c/d.org'  '/Users/evar/cellar/notes/u/w/z/x/y c/a/f.org'  -e '(?:\s*(?:\*|-|\+)\s*)(.*(?:\[|<)(jalali:[^]]+)(?:\]|>).*)'
```

I guess it's best to close this issue until I can reproduce it again. Perhaps it was some OS-level issue that got solved itself?

**Comment by genivia-inc** [comment] 2022-01-04 18:16
> @NightMachinary I guess it's best to close this issue until I can reproduce it again. Perhaps it was some OS-level issue that got solved itself?

Thanks for sharing details. I only want to know how long the pathname was, which can help to try to replicate the problem by trying out some things.

If `stat()` or `fopen()` fail due to a pathname that is too long, it is definitely an internal issue that will be difficult to work around. Just a wild guess, but perhaps the pathname contains a symbolic link that recursively points to itself or to a parent directory?

**Comment by NightMachinary** [comment] 2022-01-04 20:46
Hmm. To reiterate your hypothesis, some of the pathnames might be an infinite loop symbolic link?

I don’t think that’s the case. For one, I did not add any symbolic links between the time when things were working, and when they did not, and now that things work again. If the issue should happen again, I’ll make sure to use realpath on the arguments first, to ascertain their true true lengths.

**Comment by genivia-inc** [comment] 2022-01-04 21:41
Great. Will await your observations in the future. Let's close this one for now until further notice.

**Closed by genivia-inc** 2022-01-04 21:41 UTC

**Comment by NightMachinery** [comment] 2022-08-09 09:50
Since then, I have intermittently encountered this problem. The problem always gets resolved by doing a simple `exec zsh` which reloads the shell, so I guess the bug results from some obscure interaction between the shell and `ugrep`. Unfortunately, I have no idea how to reproduce the bug. Fortunately, it doesn't impact me much.
