### ISSUE TITLE
ugrep -v only matches once

### ISSUE THREAD

**Issue by essays-on-esotericism** [Genivia/ugrep#147] opened 2021-07-28 01:59 UTC
Hello,

I discovered some interesting behaviour with ugrep. I have a little regex I use to remove empty or commented lines from a text file:

    $ grep -Ev '^([[:space:]]*)?(#|;)|^[[:space:]]*$'

This regex is supposed to remove all lines that start with a '#' or ';' optionally preceded by an unlimited amount of whitespace. This regex works as expected on BSD grep, GNU grep and ripgrep.

To my surprise I discovered that ugrep when given the above regex will only remove the first matching line from the output:

    $ printf '; Comment 1l\n# Comment 2\n' | ugrep -Ev '^([[:space:]]*)?(#|;)|^[[:space:]]*$'

In my testing on OpenBSD 6.8 and 6.9 AMD64 with ugrep version 2.5.6 and 3.1.10 respectively, only the first matching line is stripped, and all other data is passed untouched, as if no match occurred.

I'm not sure how to debug this issue further, so I figured I'd open a bug report to share my findings.

**Comment by genivia-inc** [comment] 2021-07-28 05:05
This works fine with the latest ugrep versions (the latest is v3.3.6). a few months ago there was a change with respect to the patterns `\s` and `[[:space:]]` to exclude newlines. When a newline is matched by a space `\s` or `[[:space:]]`, then the matches do not behave as expected, even when the matching is algorithmically correct, i.e. to let `\s` and `[[:space:]]` match a newline!

**Comment by genivia-inc** [comment] 2021-07-28 05:07
Duplicate of #132.

**Closed by genivia-inc** 2021-07-28 05:07 UTC
Labels: invalid
