### ISSUE TITLE
ugrep crashes when searching ~

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#127] opened 2021-04-28 11:26 UTC
I am searching my ~ directory for a fixed string
`ugrep -ITrinF 'string' ~`

and `ugrep` crashes after a while with
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Command terminated by signal 6
```

Some results are returned, but not all.

Might be related to https://github.com/Genivia/ugrep/issues/126

**Comment by genivia-inc** [comment] 2021-04-28 14:10
Thanks for the feedback. A bad alloc is reported as an exception, not a crash. A bad alloc suggests that the allocated memory is not available. However, ugrep does not allocate much memory at all. Only if a file has very long lines without line terminations then more memory is needed to display the matching lines. Try the same with option `-o`, which does not require storing the context of long lines for display.

**Comment by genivia-inc** [comment] 2021-04-28 14:29
So to illustrate, the searches performed by each thread are guarded with:
~~~
    catch (...)
    {
      // this should never happen
      warning("exception while searching", pathname);
    }
~~~
With this the culprit should be easy to identify by the pathname. But if this is not the case, then something else outside of the search operation should be looked into as the culprit. Probably easy to fix, if we know what the input is.

**Comment by genivia-inc** [comment] 2021-04-28 17:47
Exception handling is pretty much everywhere in ugrep already to make it safe. So I can only theorize why, when and where this might happen. Perhaps in your case the issue is caused by a huge number of files searched (as expected when searching `~` recursively), but with very slow terminal output. The slow terminal output, or output that is temporarily halted, could queue up a huge number of yet-to-be executed search requests by the main thread. This in turn could overflow the `std::deque<Job>` when `std::deque<Job>::max_size` is reached or when memory cannot be allocated for some reason. However, on my system this is a whopping 576,460,752,303,423,487 so not likely to overflow the queue anytime and that is why this is unchecked. But adding a try-catch is a good idea here, to delay the queueing when the queue gets outsized until `push_back` succeeds again.

**Comment by genivia-inc** [comment] 2021-04-28 20:41
After running many recursive searches on root and home directories, I found a problem with a missing class member initialization. This is fixed in v3.1.15. All searches from root `/` and home `~` that I tried work fine now.

**Closed** 2021-04-28 20:45 UTC

**Comment by stdedos** [comment] 2021-04-28 21:34
It's nice to see that you are starting to produce more fine-grained commits/releases 😀

An unsolicited hint/advice (if I may); you cannot close multiple tickets like this:
> https://github.com/Genivia/ugrep/commit/02673baace524c7c33e2470ee980bc8291717ba5
> Fix #127 recursive search crash and related #6 #7

instead, you have to:
> Fix #127 recursive search crash and related fix #6, fix #7

https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

_My commit message does not make for perfect syntax in English, but that's the easy part to fix, I guess_ 😉

I will test the fix tomorrow

**Comment by genivia-inc** [comment] 2021-04-29 00:34
I know. It is OK, because #6 and #7 are related, but not a fix for those. Just helping out so that people searching #6 and #7 can find the latest related updates.

**Comment by stdedos** [comment] 2021-04-29 09:58
It seems that this was fixed with the new version.

Wooshing speed also! 😀 😀 😀 
0:20.02 wallclock time on a '' ~ (`-I` though)

#126 did not affect after all
