### ISSUE TITLE
`ugrep -rnw` is slow when binary file matches?

### ISSUE THREAD

**Issue by firasuke** [Genivia/ugrep#138] opened 2021-06-05 07:42 UTC
I recently stumbled upon the following issue (with `ugrep-3.3.1`) when attempting to compare the speed of `urgep` in comparison with `grep`.

I ran:

```Shell
grep/ugrep -rnw . -ie ".*pattern.*" | nl
```

The `grep` version took about a second or two to finish (I was also using `nl` and only the text that matched showed; lines that had "Binary file matches" did not get prefixed by a number).

But when I ran the `ugrep` version it reached a certain binary file (`query-cache.bin` in one of my rust projects) and ~~stayed there indefinitely even after waiting for a whole minute~~ and it took approx 5 minutes to complete compared to `grep` (another thing is that `nl` prefixed every single line of the output with the line number which is unlike GNU's `grep` behavior)!

(I believe the behavior with `nl` is related to `stdout` vs `stderr`)

So what could be the problem?

Thanks for your time!

**Comment by genivia-inc** [comment] 2021-06-05 21:14
Interesting. Thanks for the feedback.

In this case the binary file wasn't seen as a binary file at all, which means that the entire thing gets dumped which is huge! If it was marked as binary, only the message "binary file matches" is displayed like GNU grep.

This probably happened when the matching "line" (binary files can have lines too) is not binary (just pure coincidence I think), but valid Unicode text. Ugrep does not check the entire file if it is binary, only matching lines are checked. However, with option `-I` the start of the file is checked for binary. So `-I` should work in your case to ignore this file, right?

I will look into making a relatively simple change in ugrep to the binary file checking, similar to the `-I` check. This very likely will fixes this issue for you, unless `query-cache.bin` starts with a large chunk of text and not binary.

**Comment by genivia-inc** [comment] 2021-06-07 15:43
The update is ready for release in a day or so. The reason why there was a difference is related to ugrep's -X and -W options to show binary matches as hexdumps. Without these options ugrep should behave as GNU grep and just report that a binary file matches.

**Comment by firasuke** [comment] 2021-06-07 17:45
@genivia-inc Thanks for your much appreciated cooperation and for your awesome work!

`ugrep` is indeed becoming a modern and reliable (and much faster) drop-in replacement for GNU/BSD `grep`.

Keep up the great work!

**Comment by genivia-inc** [comment] 2021-06-09 13:26
I've updated ugrep to v3.3.2 to improve the binary file handling to match grep's, while adding features beyond grep. These features (e.g. `-X` hexdump, `-W` partial hexdump, `-y` display all context) can be used in many combinations with existing options (e.g. `-o` only matching, `-v` invert matches, `-An`/`-Bn`/`-Cn`). All combinations had to be thoroughly verified and tested. This ensures that the behavior is consistent with grep, but also when a new option is used such as `-y` when searching a binary file. The set of tests keeps growing.

**Closed by genivia-inc** 2021-06-09 13:26 UTC

**Comment by firasuke** [comment] 2021-06-18 17:41
Ok, so I tried running:

```Sh
ugrep -rnw . -ie ".*btmp.*"
```

on the directory resulting from extracting [zlib-ng](https://github.com/zlib-ng/zlib-ng/archive/2.0.4.tar.gz) source tarball, and it's hanging again (compared to GNU `grep` which only took 20 milliseconds to complete the search).

What could be the problem this time?

**Comment by genivia-inc** [comment] 2021-06-18 20:18
The `zlib-ng-2.0.4/test/GH-751/test.txt` file contains a single line of 18000 character long solely with 'abc' repetitions, which trips up ugrep's regex matcher. With the initial `.*` of the pattern `.*btmp.*`, this whole line needs to be reported in the result if there is a match (there is no match). This should not be a problem though. Running on `head -c 8192 test.txt` takes longer than needed to search too, taking 0.118s, so matching is slow (internal backtracking?). There is a way to optimize this initial `.*` away, to just match the non-wildcard part. Or we just have to truncate long lines to say 8K or less so that `.*` does not match 18000 characters. Right now, a line can be as long as 2GB, which is a bit much.

**Comment by genivia-inc** [comment] 2021-06-18 21:33
Ah, I already found the problem in a regex pattern search branch, where ugrep would start looking again over unmatched text. This is easy to fix and will get the algorithm back in shape to actually perform what it was designed for. It's only one line of code that should not be executed under certain but clear conditions. This combination of the file and pattern tripped this line.

**Comment by genivia-inc** [comment] 2021-06-19 00:42
Again, thanks for reporting this! This is a performance issue. This issue would've been hard to detect without the large single-line special pattern file. The pattern matching code is solid, but the optimization that was intended to deal with leading `.*` did not kick in. Without this optimization, this file takes quadratic time to match instead of linear time. So it is not hanging forever, but takes a long time with 1 file with one line of 180000 chars. I've uploaded the patch but not yet updated to the next release v3.3.3.

**Comment by firasuke** [comment] 2021-06-19 12:12
> Again, thanks for reporting this! This is a performance issue. This issue would've been hard to detect without the large single-line special pattern file. The pattern matching code is solid, but the optimization that was intended to deal with leading `.*` did not kick in. Without this optimization, this file takes quadratic time to match instead of linear time. So it is not hanging forever, but takes a long time with 1 file with one line of 180000 chars. I've uploaded the patch but not yet updated to the next release v3.3.3.

Awesome!

You're welcome, glad I could help!

**Comment by genivia-inc** [comment] 2021-06-19 15:47
Ugrep v3.3.3 is released.
