### ISSUE TITLE
[FR] ugrep -Q can remember the selections of multiple filter and then output all

### ISSUE THREAD

**Issue by jack6th** [Genivia/ugrep#57] opened 2020-07-29 15:16 UTC
It is something like the fzf -m option.   

First filtering AA.  Get 10 lines. Select 2 lines.   
And then filtering BB. Get 5 lines. Select 1 line.   
Output all 3 selected lines when quitting.   

This is not very same as filtering AA|BB.   
Because filtering AA|BB the result lines are mixed.      
The selection is not as easy as filtering two times.

**Comment by genivia-inc** [comment] 2020-07-29 15:54
Thanks for the suggestion. If I understand this right, then basically the selections made are temporarily stored and then output later (as the first selection), after making more selections (e.g. using different patterns and/or different files). This can be done by implementing a new key to press in Selection Mode to save the selections made so the user can then continue with the next selections. The next selections can be saved as well, and so on. Correct?

**Comment by genivia-inc** [comment] 2020-07-29 21:02
Here is what I've implemented in a prototype version of ugrep with the updated query UI.

When pressing `Enter`, selection mode is activated and it has two new features `S` for save and `D` to delete saved (note that I had to condense the top line to fit 80 column screens):

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13117347/88852327-1edbce80-d1bc-11ea-9019-f6b1f8e71197.png">

Select a couple of lines with `Enter`, for example the top 3, then press `S` to save them, which shows the number of lines saved and returns to the search query:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13117347/88852541-68c4b480-d1bc-11ea-85d7-63cd26f9d896.png">

More selections can be made and saved at any time. The total number of lines is confirmed by a message. The selected lines will be output when exiting ugrep.

Pressing `D` in selection mode deletes all of the saved lines, just in case a mistake was made and we want to start over.

I like this. This works quite well.

**Comment by jack6th** [comment] 2020-07-30 00:25
Good.   
And the selected lines should be marked.   
If the result lines of BB filter include the lines which were already selected in filter AA, user can choose to keep it selected or to deselect it.

**Comment by genivia-inc** [comment] 2020-07-30 01:34
The screen shot does not show it, but after saving the lines the search prompt reappears and the lines that were selected are no longer marked (not selected). There are four possible actions that can be implemented when typing `S`:

1. as I mentioned above, `S` saves the lines, returns to the Q> prompt and unmarks the lines selected
2. `S` saves the lines, returns to the Q> prompt but does not unmark the lines selected (however, entering a pattern unmarks lines)
3. `S` saves the lines, does not return to the Q> prompt, unmarks the lines selected
4. `S` saves the lines, does not return to the Q> prompt, keeps the lines selected

Are you suggesting 2 above? Note that if we keep the lines selected and the user exits the program than the selected lines will be output twice, once for the saved lines and once more for the selected lines still in view. I see that is a potential problem, meaning that users may end up with accidentally duplicating the lines they selected. I think it is best to deselect all lines after saving them, because that avoids possible duplication of all of them in the output when exiting. When exiting, the saved lines and the lines that are selected in the current view are output. So nothing ends up getting lost.

**Comment by jack6th** [comment] 2020-07-30 03:18
Not all of above.   
S saves the lines, returns to the Q> prompt but does not unmark the lines selected.  Entering a pattern does not unmarks lines if the lines are in the same file and having the same line number.  And only output marked lines once.

**Comment by genivia-inc** [comment] 2020-07-30 12:59
So it is more like locking the selected lines in place rather than saving them?

**Comment by jack6th** [comment] 2020-07-30 15:18
The end selected output lines are same.   
AA|BB get 15 lines.   Mixed AA and BB results.   
I mean the ugrep result lines match a pattern, not the select or output lines.

**Comment by jack6th** [comment] 2020-07-30 22:05
I think locking the selected lines is the best choice.   
And the choice 1 you mentioned above is also acceptable.  But ugrep should provide an option to remove duplicates.  
Or user need pipe the output lines to remove duplicates.  This is not very convenient.   
```
ugrep -Q filenames | awk '!a[$0]++'
```

**Comment by genivia-inc** [comment] 2020-07-31 13:41
I need some time to think about ways for possible improvements and their pro/cons, while not impacting the search performance. By contrast to fzf, ugrep has no limits on the amount of output generated by design. If for example in the extreme case you use the query UI at the root of the file system and 'select all' in selection mode, then in fact it will output every file found on your system that is readable. This will not fit in memory when internally saved to memory. Right now, the algorithm considers lines marked versus 'select all' to produce all output.

**Comment by jack6th** [comment] 2020-08-01 20:24
On windows fzf does not support mulitbyte characters very well.  ( UTF-8 ) 
Most of time when quitting it exit the terminal window instead of exiting fzf. And having some problem when displaying CJK.    
Ugrep has no these problem.

**Comment by genivia-inc** [comment] 2021-03-23 21:29
I'm closing this for now (but may reopen perhaps later) for two reasons: firstly I haven't come across many use cases that are really important to have this feature, and secondly because making selections across multiple files can also simply be done by running ugrep -Q multiple times to append each search result to a single output file to browse or use as the total result. For example like this in bash:
~~~
rm results.txt
while ugrep -Q -e 'xxxxxxxxxxxx' >> results.txt; do echo; done
~~~
Here we use pattern `-e xxxxxxxxxxxx` to not match anything, so exiting ugrep does not produce output to terminate the loop. Grep tools exit with nonzero if the search did not produce any hits.

**Closed by genivia-inc** 2021-03-23 21:29 UTC
Labels: enhancement
