### ISSUE TITLE
Unexpected results with redundant parentheses in boolean regexes

### ISSUE THREAD

**Issue by zmajeed** [Genivia/ugrep#223] opened 2022-08-14 13:38 UTC
I'm trying out the great boolean expressions feature - first off, thanks for doing it!

Could you shed light on these boolean expressions with redundant grouping parentheses?

Here's the test file

```bash
$ cat test1.txt
1. abc
2. xyz abc
3. def
4. ghi
```

1. This query has redundant parentheses but the result is expected

```bash
$ ugrep --stats --bool "((abc xyz) OR def)" test1.txt
2. xyz abc
3. def

Lines matched if:
  "abc|def" matches, and
  "xyz|def" matches
```
2. Redundant parentheses again and result is fine

```bash
$ ugrep --stats --bool "(abc xyz)" test1.txt
2. xyz abc

Lines matched if:
  "abc" matches, and
  "xyz" matches
```
3. This is unexpected with two pairs of redundant parentheses - there are no results for what is logically the same as query 2

```bash
$ ugrep --stats --bool "((abc xyz))" test1.txt

Lines matched if:
  "(abc xyz)" matches
```

4. This wrongly returns line 1 as a match - also matches were not colored - and --stats did not print query in CNF

```bash
$ ugrep --stats --bool "((abc xyz) OR def) OR ghi" test1.txt
1. abc
2. xyz abc
3. def
4. ghi

Searched 1 file in 0.002 seconds: 1 matching (100%)
Searched 5 lines: 5 matching (100%)
The following pathname selections and search restrictions were applied:
  --dereference
  --no-hidden (default)
```

5. Removing redundant parentheses in query 4 gives correct results with color

```bash
$ ugrep --stats --bool "(abc xyz) OR def OR ghi" test1.txt
2. xyz abc
3. def
4. ghi

Lines matched if:
  "abc|def|ghi" matches, and
  "xyz|def|ghi" matches
```

**Comment by genivia-inc** [comment] 2022-08-14 17:57
Thanks for the feedback. I already thought long and hard about this before releasing ugrep with Boolean queries. There are problems with your assessment:

Firstly, note that the inner parenthesis are part of the regex form because of the lack of surrounding spacing. Outer parenthesis are part of the Boolean query, but. _Boolean subexpressions require spacing before or after._ For example, `( (abc xyz) )` is a Boolean query with both parenthesis part of the Boolean query, whereas `((abc xyz))` has no extra spacing. You can see this in case (4) where there is a space after the `xyz)` parenthesis which makes it part of the Boolean query.

Secondly, the reason for this design choice is that if parenthesis are too greedily considered to be part of the Boolean query, then _it can become impossible to use parenthesis in regex forms_. Also, spacing in a regex is valid and must be possible to use in a regex. For example, `((abc)*(xyz))` has a similar structure `((...))` but is clearly `(abc)*(xyz)` as a regex and so should `(abc) (xyz)` be a regex and also `(abc xyz)`. No surprise here. Just use spacing with Boolean query operators `AND` and `OR` and parenthesis as the documentation says.

**Comment by genivia-inc** [comment] 2022-08-20 19:26
I'm closing this because it should be clear from `ugrep --help regex` which regex patterns are used in a Boolean query syntax. The spacing of Boolean query operators is relevant when combined with parenthesis. The `(abc xyz)` is a regex pattern inside a Boolean query, and the parenthesis in `(abc xyz)` _are part of the Boolean query if a Boolean operator is used before or after_ `(abc xyz)` as you've also observed. This is by design, since spacing and parenthesis can be part of a regex expression.

**Closed by genivia-inc** 2022-08-20 19:26 UTC
Labels: invalid, question, works as documented
